# Generated by Django 2.0.2 on 2018-02-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeposter', '0003_remove_codepost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepost',
            name='header',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='language_name',
            field=models.CharField(max_length=50),
        ),
    ]
